repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.13.1
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix]
          # Run the formatter.
          - id: ruff-format
    - repo: local
      hooks:
          - id: ty
            name: ty
            entry: uv run ty check
            language: python
            types: [python]
