model: "anthropic:claude-sonnet-4-0"

name: "customer-support-agent"

instructions:
    - "You are a helpful customer support agent"
    - "Always be polite and professional"
    - "Ask clarifying questions when needed"

system_prompt: "Use the customer's name when addressing them"

model_settings:
    timeout: 30.0

tools: []
builtin_tools: []
